# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

#==============Monitors Resolution Settings================

monitor = eDP-1, 1920x1080@60, auto, 1.25

monitor = HDMI-A-2, 1920x1080@60,auto,1.25

#==============Mouse Senstivity Settings===================



input {
    # -1.0 to 1.0, 0 means no modification.
    sensitivity = 0

}

# device {
#    name = razer-razer-deathadder-essential
#     sensitivity = -0.6
# }
# device {
#    name = razer-razer-deathadder-essential-1
#     sensitivity = -0.6
# }



# HDMI port: mirror display. To see device name, use `hyprctl monitors`
